token: "TOKEN"
group_id: 0
# Доступные значения:
# {nick} - ник игрока;
# {activity} | (в переводе "Деятельность") - то, чем будет заниматься игрок на сервере
# {playtime} - количество лет/месяцев/недель/дней, или же точная дата.
text:
  - "Заявка на вступление на сервер:"
  - "1. Ник: {nick}"
  - "2. Деятельность: {activity}"
  - "3. Сколько лет играете в майнкрафт: {playtime}"